-- Generated from the balanced local catalog; preserve legacy rarity by card name, never by reused ID.
insert into public.store_catalog(id,name,element,card_type) values
('ARFT_BLD_0001','Katana of Fate','blood','artifact'),
('ARFT_BLD_0002','The Generals Armor','blood','artifact'),
('ARFT_BLD_0003','Blood Pendant','blood','artifact'),
('ARFT_BLD_0004','Vampiric Destiny','blood','artifact'),
('CTRL_BLD_0001','RenLarKu','blood','controller'),
('CTRL_BLD_0002','Blood Weaver','blood','controller'),
('CTRL_BLD_0003','Blood Lord','blood','controller'),
('CRTE_BLD_0001','Blood General','blood','creature'),
('CRTE_BLD_0002','Crimson Knight','blood','creature'),
('CRTE_BLD_0003','Blood Knight','blood','creature'),
('CRTE_BLD_0004','Redeemed Knight','blood','creature'),
('CRTE_BLD_0005','Reaper','blood','creature'),
('CRTE_BLD_0006','Blood Witch','blood','creature'),
('CRTE_BLD_0007','Blood Swarm','blood','creature'),
('CRTE_BLD_0008','Ren','blood','creature'),
('SPEL_BLD_0001','Zombie''s Day','blood','spell'),
('SPEL_BLD_0002','Blood Bond','blood','spell'),
('SPEL_BLD_0003','Blood Ritual','blood','spell'),
('SPEL_BLD_0004','Blood Magic','blood','spell'),
('SPEL_BLD_0005','Soul Siphon','blood','spell'),
('SPEL_BLD_0006','Lifeblood','blood','spell'),
('SPEL_BLD_0007','Mist of Fate','blood','spell'),
('ARFT_CYO_0001','Sphere of Ice','cryo','artifact'),
('ARFT_CYO_0002','Enchanted Ice Crystal','cryo','artifact'),
('CTRL_CYO_0001','CyRelli Princess','cryo','controller'),
('CTRL_CYO_0002','Guardian Princess','cryo','controller'),
('CTRL_CYO_0003','Royal Ice Knight','cryo','controller'),
('CRTE_CYO_0001','CyRelli''s Tiger','cryo','creature'),
('CRTE_CYO_0002','Frost Wyrm','cryo','creature'),
('CRTE_CYO_0003','Ice Yetti','cryo','creature'),
('CRTE_CYO_0004','Frozen Troll','cryo','creature'),
('CRTE_CYO_0005','Frozen Golem','cryo','creature'),
('CRTE_CYO_0006','Ice Protector','cryo','creature'),
('CRTE_CYO_0007','Frozen Knight','cryo','creature'),
('CRTE_CYO_0008','Cryo Mage','cryo','creature'),
('CRTE_CYO_0009','Frozen Spirit','cryo','creature'),
('SPEL_CYO_0001','Frozen Barrage','cryo','spell'),
('SPEL_CYO_0002','Ice Breath','cryo','spell'),
('SPEL_CYO_0003','Freezing Spell','cryo','spell'),
('SPEL_CYO_0004','Blizzard','cryo','spell'),
('SPEL_CYO_0005','White Out','cryo','spell'),
('SPEL_CYO_0006','Defrost','cryo','spell'),
('ARFT_ETH_0001','Earth Staff','earth','artifact'),
('ARFT_ETH_0002','Enchanted Emerald','earth','artifact'),
('CTRL_ETH_0001','Earth Spirit','earth','controller'),
('CTRL_ETH_0002','Earth Defender','earth','controller'),
('CTRL_ETH_0003','Giant','earth','controller'),
('CRTE_ETH_0001','Guardian of the Tree','earth','creature'),
('CRTE_ETH_0002','Moss Dragon','earth','creature'),
('CRTE_ETH_0003','Earth Serpent','earth','creature'),
('CRTE_ETH_0004','Earth Knight','earth','creature'),
('CRTE_ETH_0005','Ogre Attacker','earth','creature'),
('CRTE_ETH_0006','Witch of Nature','earth','creature'),
('CRTE_ETH_0007','Gnome Warlock','earth','creature'),
('CRTE_ETH_0008','Wolfen','earth','creature'),
('CRTE_ETH_0009','Goblin Knight','earth','creature'),
('CRTE_ETH_0010','Golem Defender','earth','creature'),
('SPEL_ETH_0001','Tree of Life','earth','spell'),
('SPEL_ETH_0002','Nature''s Bliss','earth','spell'),
('SPEL_ETH_0003','Vine Tree','earth','spell'),
('SPEL_ETH_0004','Vine Coffin','earth','spell'),
('SPEL_ETH_0005','Nature''s Blade','earth','spell'),
('ARFT_ELC_0001','Lightning Stone','electric','artifact'),
('ARFT_ELC_0002','Lightning Gauntlet','electric','artifact'),
('ARFT_ELC_0003','Spark Knight Blade','electric','artifact'),
('CTRL_ELC_0001','The Luminary','electric','controller'),
('CTRL_ELC_0002','Spark White Dragon','electric','controller'),
('CTRL_ELC_0003','Spark Knight','electric','controller'),
('CRTE_ELC_0001','Volt-Howler','electric','creature'),
('CRTE_ELC_0002','Lightning Giant','electric','creature'),
('CRTE_ELC_0003','Lightning Samurai','electric','creature'),
('CRTE_ELC_0004','Lightning Zephyr Knight','electric','creature'),
('CRTE_ELC_0005','Viking of Light','electric','creature'),
('CRTE_ELC_0006','Lightning Knight','electric','creature'),
('CRTE_ELC_0007','Lightning Mage','electric','creature'),
('CRTE_ELC_0008','Lightning Wielder','electric','creature'),
('CRTE_ELC_0009','Cosmic Witch','electric','creature'),
('CRTE_ELC_0010','Spirit of Lightning','electric','creature'),
('CRTE_ELC_0011','Zephyr','electric','creature'),
('SPEL_ELC_0001','Binding Chains of Lightning','electric','spell'),
('SPEL_ELC_0002','Surreal Light','electric','spell'),
('SPEL_ELC_0003','Wolf Lightning Strike','electric','spell'),
('ARFT_FIR_0001','Cursed Flame Sword','fire','artifact'),
('ARFT_FIR_0002','Flame Orb','fire','artifact'),
('ARFT_FIR_0003','Draco''s Slayer','fire','artifact'),
('CTRL_FIR_0001','Draco Alec','fire','controller'),
('CTRL_FIR_0002','Flame Emperor','fire','controller'),
('CTRL_FIR_0003','Supreme Fire Spirit','fire','controller'),
('CRTE_FIR_0001','Draco','fire','creature'),
('CRTE_FIR_0002','Emperor''s Fire Dragon','fire','creature'),
('CRTE_FIR_0003','Flame Dragon','fire','creature'),
('CRTE_FIR_0004','Fire Paladin','fire','creature'),
('CRTE_FIR_0005','Flame Samurai','fire','creature'),
('CRTE_FIR_0006','Fire Knight','fire','creature'),
('CRTE_FIR_0007','Flaming Sword Bearer','fire','creature'),
('CRTE_FIR_0008','Flame Guardian','fire','creature'),
('CRTE_FIR_0009','Flame Wolf','fire','creature'),
('CRTE_FIR_0010','Fire Witch','fire','creature'),
('CRTE_FIR_0011','Flame Warlock','fire','creature'),
('SPEL_FIR_0001','Draco''s Inferno','fire','spell'),
('SPEL_FIR_0002','Draco''s Curse','fire','spell'),
('SPEL_FIR_0003','Enflamed','fire','spell'),
('ARFT_LGT_0001','Dagger of Fate','light','artifact'),
('ARFT_LGT_0002','Sword of the Sun Guardian','light','artifact'),
('CTRL_LGT_0001','Cosmic Sunlight Goddess','light','controller'),
('CTRL_LGT_0002','Perfect Light Being','light','controller'),
('CTRL_LGT_0003','Light Priest','light','controller'),
('CRTE_LGT_0001','Michael','light','creature'),
('CRTE_LGT_0002','Light Dragon','light','creature'),
('CRTE_LGT_0003','Sun Golem','light','creature'),
('CRTE_LGT_0004','Sun Guardian','light','creature'),
('CRTE_LGT_0005','Sun Commander','light','creature'),
('CRTE_LGT_0006','Sun Knight','light','creature'),
('CRTE_LGT_0007','Radiant Witch','light','creature'),
('CRTE_LGT_0008','Sun Mage','light','creature'),
('CRTE_LGT_0009','Sun Wolf','light','creature'),
('CRTE_LGT_0010','Sun Fairy','light','creature'),
('CRTE_LGT_0011','Light Spirit','light','creature'),
('SPEL_LGT_0001','Divine Light','light','spell'),
('SPEL_LGT_0002','Light Bind','light','spell'),
('SPEL_LGT_0003','Burning Blast','light','spell'),
('SPEL_LGT_0004','Light Enchantment','light','spell'),
('SPEL_LGT_0005','Divine Elemental Convergence','light','spell'),
('ARFT_SHD_0001','Thor''s Hammer','shadow','artifact'),
('ARFT_SHD_0002','Cursed Sword','shadow','artifact'),
('ARFT_SHD_0003','Dark Orb','shadow','artifact'),
('CTRL_SHD_0001','Darth Ayres','shadow','controller'),
('CTRL_SHD_0002','Umbra Reaver','shadow','controller'),
('CTRL_SHD_0003','Shadow Master','shadow','controller'),
('CRTE_SHD_0001','Dark Samurai','shadow','creature'),
('CRTE_SHD_0002','Dark Phantom','shadow','creature'),
('CRTE_SHD_0003','Dark Knight','shadow','creature'),
('CRTE_SHD_0004','Shadow Knight','shadow','creature'),
('CRTE_SHD_0005','Dark Warlock','shadow','creature'),
('CRTE_SHD_0006','Sigurd Shadowhand','shadow','creature'),
('CRTE_SHD_0007','Shadow Wraith','shadow','creature'),
('CRTE_SHD_0008','Night Terror','shadow','creature'),
('SPEL_SHD_0001','Dark Dimension','shadow','spell'),
('SPEL_SHD_0002','Black Spell','shadow','spell'),
('SPEL_SHD_0003','Dark Ritual','shadow','spell'),
('SPEL_SHD_0004','Shadow''s Embrace','shadow','spell'),
('SPEL_SHD_0005','Dark Chains','shadow','spell'),
('SPEL_SHD_0006','Shadow Spell','shadow','spell'),
('SPEL_SHD_0007','Dark Nova','shadow','spell'),
('SPEL_UNI_0001','Elemental Convergence','universal','spell'),
('SPEL_UNI_0002','Creature Recall','universal','spell'),
('ARFT_WTR_0001','Spear of Neptune','water','artifact'),
('ARFT_WTR_0002','Crown of Neptune','water','artifact'),
('CTRL_WTR_0001','Neptune','water','controller'),
('CTRL_WTR_0002','The Kraken','water','controller'),
('CTRL_WTR_0003','Mermaid Empress','water','controller'),
('CRTE_WTR_0001','Supreme Water Dragon','water','creature'),
('CRTE_WTR_0002','Water Golem','water','creature'),
('CRTE_WTR_0003','Guardians of Atlantis','water','creature'),
('CRTE_WTR_0004','Shark','water','creature'),
('CRTE_WTR_0005','Royal Guard','water','creature'),
('CRTE_WTR_0006','Lizard Warrior','water','creature'),
('CRTE_WTR_0007','Water Warlock','water','creature'),
('CRTE_WTR_0008','Water Guardian','water','creature'),
('CRTE_WTR_0009','Water Familiar','water','creature'),
('SPEL_WTR_0001','Whirlpool','water','spell'),
('SPEL_WTR_0002','Water Entrapment','water','spell'),
('SPEL_WTR_0003','Kraken Slash','water','spell'),
('SPEL_WTR_0004','Tidal Wave','water','spell'),
('SPEL_WTR_0005','Dragon''s Tsunami','water','spell'),
('SPEL_WTR_0006','Water Safe','water','spell'),
('ARFT_WID_0001','Wind Orb','wind','artifact'),
('ARFT_WID_0002','Wind Staff','wind','artifact'),
('ARFT_WID_0003','Wind Sword','wind','artifact'),
('CTRL_WID_0001','Wind Knight','wind','controller'),
('CTRL_WID_0002','Wind Witch','wind','controller'),
('CTRL_WID_0003','Spirit of the Wind','wind','controller'),
('CRTE_WID_0001','Wind Dragon','wind','creature'),
('CRTE_WID_0002','Wind Golem','wind','creature'),
('CRTE_WID_0003','Wind Ronin','wind','creature'),
('CRTE_WID_0004','Wind Warrior','wind','creature'),
('CRTE_WID_0005','Wind Warlock','wind','creature'),
('CRTE_WID_0006','Wind Keeper','wind','creature'),
('CRTE_WID_0007','Wind Pack','wind','creature'),
('SPEL_WID_0001','Tempest','wind','spell'),
('SPEL_WID_0002','Wind Control','wind','spell'),
('SPEL_WID_0003','Sweeping Wind','wind','spell'),
('SPEL_WID_0004','Spell Release','wind','spell'),
('SPEL_WID_0005','Dark Infusion','wind','spell'),
('SPEL_WID_0006','Wind Protection','wind','spell'),
('SPEL_WID_0007','Smoke Body','wind','spell'),
('SPEL_WID_0008','Wind Mirage','wind','spell')
on conflict(id) do update set name=excluded.name,element=excluded.element,card_type=excluded.card_type;
update public.store_catalog s set rarity=coalesce((select c.rarity from public.card c where lower(regexp_replace(c.name,'[^a-zA-Z0-9]','','g'))=lower(regexp_replace(s.name,'[^a-zA-Z0-9]','','g')) limit 1),'common');
insert into public.store_legacy_cards(legacy_id,card_id) select c.code,s.id from public.card c join public.store_catalog s on lower(regexp_replace(c.name,'[^a-zA-Z0-9]','','g'))=lower(regexp_replace(s.name,'[^a-zA-Z0-9]','','g')) on conflict(legacy_id) do update set card_id=excluded.card_id;
