// Explicit, reviewable card rules. Printed descriptions are never parsed at runtime.
const need = (condition, message) => { if (!condition) throw new Error(message); };
const active = (label, run, cost = 0, ch = 0) => ({ label, run, cost, ch });
const allies = c => c.me.creatures.filter(Boolean);
const enemies = c => c.enemy.creatures.filter(Boolean);
const elemental = (c, element) => allies(c).filter(u => u.card.element === element);
const buffAura = (c, element, ap = 0, ch = 0, others = false) => elemental(c, element).filter(u => !others || u.uid !== c.source.uid).forEach(u => { u.currentAP += ap; u.maxCH += ch; });
const equipAura = (c, ap = 0, ch = 0, traits = {}) => { const u = c.targetUnit(); if (u) { u.currentAP += ap; u.maxCH += ch; Object.assign(u.traits, traits); } };
const freeze = (c, u, n = 1) => c.status(u, 'Frozen', { remaining: n });
const paralyze = (c, u, n = 1, dot = 0) => c.status(u, 'Paralyzed', { remaining: n, dot });
const bind = (c, u, n, cannotDefend = false) => c.status(u, 'Bound', { remaining: n, ...(cannotDefend ? { trait: 'cannotDefend' } : {}) });
const sacrifice = c => { const u = c.target('ally creature', false, u => !u.traits.cannotSacrifice); c.destroy(u, 'sacrifice'); return u; };
const healController = (c, n) => c.heal(c.controller(), n);
const spellArea = (c, n) => c.aoe(n);
const durationBuff = (c, u, ap) => c.buff(u, ap, 0, 'end');
const attackTwice = (c, u) => c.status(u, 'Double attack', { end: c.g.turnNumber });
const haste = (c, u) => c.status(u, 'Haste', { trait: 'haste', end: c.g.turnNumber });
const destroyEnd = (c, u, extra = {}) => c.status(u, 'Doomed', { end: c.g.turnNumber, destroy: true, ...extra });
const copyFrom = (c, name) => { const card = c.byName[name]; if (card) c.me.hand.push(structuredClone(card)); };
const shield = (c, u, trait, duration = 'source') => c.status(u, trait, { trait, ...(duration === 'end' ? { end: c.g.turnNumber } : typeof duration === 'number' ? { remaining: duration } : { source: c.source.uid }) });
const silence = (c, u, n = 1) => c.status(u, 'Silenced', { remaining: n });
const onOwnTurn = (c, side) => c.side === side;
const attached = (c, name, u = c.source) => c.attached(u).some(a => a.card.name === name);

export const definitions = {
  // BLOOD
  'Katana of Fate': { equip: true, aura(c) { const u = c.targetUnit(); if (!u) return; u.currentAP += u.card.element === 'blood' ? 2 : 1; if (['Blood General', 'Ren'].includes(u.card.name)) u.currentAP += c.named('RenLarKu')?.currentAP || 0; } },
  'The Generals Armor': { equip: true, aura: c => equipAura(c, 0, 0, { spellImmune: true }) },
  'Blood Pendant': { equip: true, onDamage: c => c.me.nextShards++ },
  'Vampiric Destiny': {
    equip: 'ally creature', onPlay(c) { c.search(card => card.card_type === 'creature' && card.name.includes('Swarm')); const u = c.target('any unit'); c.buff(u, 0, c.targetUnit()?.card.ch || 0); },
    turnStart(c, side) { if (!onOwnTurn(c, side) || !c.source.flags.returnCard) return; const card = c.source.flags.returnCard; const grave = c.g[c.source.flags.returnOwner].graveyard; const index = grave.findIndex(v => v.id === card.id); delete c.source.flags.returnCard; if (index < 0) return; grave.splice(index, 1); if (c.me.creatures.some(u => !u)) c.summon(card); else c.me.hand.push(card); },
  },
  'RenLarKu': { active: [active('Blood draw', c => c.draw(), 0, 1), active('Empower creature', c => durationBuff(c, c.target('any creature'), 1))] },
  'Blood Weaver': { active: [active('Sacrificial ascension', c => { need(allies(c).filter(u => !u.traits.cannotSacrifice).length >= 2, 'Requires two sacrificable creatures.'); sacrifice(c); sacrifice(c); const card = c.search(card => card.card_type === 'controller', ['hand', 'deck', 'graveyard']); if (card) { c.me.hand.splice(c.me.hand.indexOf(card), 1); c.summon(card, { controller: true }); } }), active('Blood restraint', c => paralyze(c, c.target('enemy unit')), 0, 2)] },
  'Blood Lord': { turnStart(c, side) { if (onOwnTurn(c, side) && !allies(c).length) { c.damage(c.controller(c.opponent), 1); healController(c, 1); } }, active: [active('Blood nova', c => spellArea(c, 2), 3)] },
  'Blood General': { aura: c => buffAura(c, 'blood', 1, 0, true) },
  'Crimson Knight': { traits: { cannotSacrifice: true } },
  'Blood Knight': { aura(c) { if (c.controller()?.damage === 0) c.source.maxCH += 2; } },
  'Redeemed Knight': { onDeath: c => healController(c, 3) },
  'Reaper': {},
  'Blood Witch': { onPlay: c => c.search(card => card.element === 'blood' && card.card_type === 'spell', ['graveyard']) },
  'Blood Swarm': { active: [active('Summon swarm', c => c.token('Swarm Token', 1, 1, 2), 0, 1)] },
  'Ren': { /* Katana computes RenLarKu's bonus once, including the Ren synergy. */ },
  "Zombie's Day": { onPlay: c => c.flag('zombieTurn', c.g.turnNumber) },
  'Blood Bond': { require: c => need(c.has('Blood Weaver'), 'Blood Weaver is required.'), onPlay: c => c.steal(c.target('enemy creature')) },
  'Blood Ritual': { onPlay(c) { sacrifice(c); c.gain(3, true); } },
  'Blood Magic': { onPlay(c) { const u = c.target('any creature'); durationBuff(c, u, 3); destroyEnd(c, u); } },
  'Soul Siphon': { onPlay(c) { c.damage(c.target('any creature'), 2); if (c.controller()?.card.element === 'blood') healController(c, 2); } },
  'Lifeblood': { onPlay(c) { const targets = allies(c); need(targets.length && !targets.some(u => u.traits.cannotSacrifice), 'All creatures must be sacrificable.'); const ch = targets.reduce((n, u) => n + u.currentCH, 0); const ctrl = c.target('ally controller'); for (const u of targets) c.destroy(u, 'sacrifice'); c.buff(ctrl, 0, ch); } },
  'Mist of Fate': { onPlay(c) { if (c.controller()?.card.element !== 'blood' && c.random() < .5) { c.note('Mist of Fate: coin flip failed.'); return; } if (enemies(c).length) c.destroy(c.target('enemy creature')); else { c.damage(c.controller(c.opponent), 2); healController(c, 2); } } },
  // CRYO
  'Sphere of Ice': { equip: 'ally controller', onPlay(c) { c.source.flags.lostAP = 0; if (c.targetUnit()?.card.name === 'Guardian Princess') c.fromZone(['Ice Protector', 'Frozen Knight']); }, aura: c => equipAura(c, Math.max(0, 3 - (c.source.flags.lostAP || 0))), unitDied(c, { unit }) { if (unit.zone === 'creatures') c.source.flags.lostAP++; } },
  'Enchanted Ice Crystal': {},
  'CyRelli Princess': { onPlay: c => c.fromZone(["CyRelli's Tiger"]), unitDied(c, { unit, cause }) { if (unit.side === c.side && unit.card.name === "CyRelli's Tiger" && cause !== 'combat') c.buff(c.source, 0, 5); } },
  'Guardian Princess': { aura(c) { if (c.has('Sphere of Ice')) buffAura(c, 'cryo', 0, 2); }, active: [active('Royal protection', c => shield(c, c.target('ally unit'), 'battleImmune', 'end'), 3)] },
  'Royal Ice Knight': { aura(c) { for (const u of c.units()) if (u.statuses.Frozen) u.currentAP += 2; }, active: [active('Summon frost wyrm', c => { c.token('Royal Wyrm', 3, 3, 1, { haste: true }); const u = allies(c).findLast(u => u.card.name === 'Royal Wyrm'); if (u) destroyEnd(c, u); }, 2)] },
  "CyRelli's Tiger": { traits: { cannotAttack: true }, aura(c) { const princess = c.named('CyRelli Princess'); if (princess) princess.currentAP += 5; } },
  'Frost Wyrm': {},
  'Ice Yetti': { onAttack(c, u) { if (u.zone !== 'creatures') return; const index = c.enemy.creatures.indexOf(u); c.enemy.creatures.slice(Math.max(0, index - 1), index + 2).filter(Boolean).forEach(v => freeze(c, v)); } },
  'Frozen Troll': { turnStart(c, side) { if (onOwnTurn(c, side)) c.heal(c.source, 2); } },
  'Frozen Golem': { traits: { guardian: true } },
  'Ice Protector': { onDeath(c, { killer }) { if (killer) freeze(c, killer, 2); } },
  'Frozen Knight': { onDamage(c, u) { if (u.zone === 'creatures') freeze(c, u); } },
  'Cryo Mage': { onPlay: c => { const u = c.target('enemy creature', true); if (u) freeze(c, u); } },
  'Frozen Spirit': { onDamage: c => c.bounce(c.source) },
  'Frozen Barrage': { require: c => need(!allies(c).length, 'Requires no allied creatures.'), onPlay(c) { for (const u of [...enemies(c)]) { if (u.currentAP <= 3) c.destroy(u); else c.bounce(u); } } },
  'Ice Breath': { onPlay(c) { need(c.has('Frost Wyrm') || c.enemy.controllers.some(u => u?.card.element === 'cryo'), 'Requires Frost Wyrm or an enemy Cryo controller.'); const n = c.has('Frost Wyrm') ? 3 : 1; c.units(c.opponent).forEach(u => paralyze(c, u, n)); } },
  'Freezing Spell': { onPlay: c => c.units(c.opponent).forEach(u => paralyze(c, u)) },
  'Blizzard': { onPlay: c => [...allies(c), ...enemies(c)].filter(u => u.card.element !== 'cryo').forEach(u => freeze(c, u)) },
  'White Out': { onPlay: c => enemies(c).forEach(u => c.buff(u, -2, 0, 1, 'White Out')) },
  'Defrost': { onPlay(c) { const u = c.target('ally creature'); for (const key of ['Frozen', 'Paralyzed', 'Bound']) delete u.statuses[key]; durationBuff(c, u, 3); if (c.has('Royal Ice Knight')) c.search(['Blizzard', 'White Out']); } },
  // EARTH
  'Earth Staff': { equip: true, aura: c => equipAura(c, 0, 4) },
  'Enchanted Emerald': { turnStart(c, side) { if (onOwnTurn(c, side) && c.me.turns % 2 === 0) c.gain(1); } },
  'Earth Spirit': { unitPlayed(c, u, side) { if (side === c.side && u.zone === 'creatures' && u.card.element === 'earth' && c.source.flags.gainedTurn !== c.g.turnNumber) { c.gain(1); c.source.flags.gainedTurn = c.g.turnNumber; } }, active: [active('Nature’s calling', c => c.search(['Enchanted Emerald', 'Guardian of the Tree'], ['deck']), 2)] },
  'Earth Defender': { active: [active('Entangling roots', c => paralyze(c, c.target('enemy unit'), 2, 2), 3)] },
  'Giant': { onAttack(c) { if (c.attached().length) c.discard(); }, active: [active('Earthquake', c => spellArea(c, 3), 4)] },
  'Guardian of the Tree': { onPlay: c => c.search(['Vine Tree', 'Vine Coffin']), turnEnd(c, side) { if (side === c.side) elemental(c, 'earth').forEach(u => c.heal(u, 2)); } },
  'Moss Dragon': { traits: { reduction: 2 } },
  'Earth Serpent': { aura(c) { if (elemental(c, 'earth').some(u => u.uid !== c.source.uid)) c.source.traits.untargetable = true; } },
  'Earth Knight': { onPlay(c) { const u = c.target('ally unit'); c.buff(u, 0, 3); c.status(u, 'Freeze immunity', { trait: 'freezeImmune' }); } },
  'Ogre Attacker': { onAttack(c, u) { if (c.attached(u).length) c.destroy(u, 'ability'); else { c.damage(c.source, 1); paralyze(c, c.source); } } },
  'Witch of Nature': { onPlay: c => c.heal(c.target('ally unit'), 3), onAttack(c) { if (attached(c, 'Earth Staff')) { const u = c.units().sort((a, b) => a.currentCH - b.currentCH)[0]; c.heal(u, 2); } } },
  'Gnome Warlock': { unitDied(c, { unit }) { if (unit.side === c.side && unit.card.element === 'earth' && c.source.flags.gainedTurn !== c.g.turnNumber) { c.gain(1); c.source.flags.gainedTurn = c.g.turnNumber; } } },
  'Wolfen': { traits: { haste: true }, aura(c) { if (allies(c).some(u => u.uid !== c.source.uid && ['Wolfen', 'Goblin Knight'].includes(u.card.name))) c.source.currentAP += 2; } },
  'Goblin Knight': { onPlay(c) { if (!c.source.flags.suppressRecruit && c.me.creatures.some(u => !u)) c.fromZone(['Goblin Knight'], ['hand', 'deck'], { suppressRecruit: true }); } },
  'Golem Defender': { traits: { guardian: true } },
  'Tree of Life': { onPlay(c) { const guardian = c.named('Guardian of the Tree'); if (!guardian) { c.search(['Earth Staff']); return; } const targets = allies(c).filter(u => u !== guardian); const amount = targets.reduce((n, u) => n + u.currentCH, 0); for (const u of targets) c.destroy(u, 'ability'); c.buff(guardian, -guardian.currentAP, amount); c.status(guardian, 'Tree guardian', { trait: 'guardian' }); } },
  "Nature's Bliss": { onPlay(c) { const witch = c.named('Witch of Nature'); if (witch) { for (const name of ['Earth Staff', "Nature's Blade"]) { const card = c.me.hand.find(v => v.name === name); if (card) c.playFree(card, witch); } } else c.fromZone(['Gnome Warlock', 'Goblin Knight'], ['hand']); } },
  'Vine Tree': { onPlay: c => c.token('Wall of Vines', 0, 5, 2, { guardian: true }) },
  'Vine Coffin': { onPlay: c => paralyze(c, c.target('enemy creature'), 2, 2) },
  "Nature's Blade": { onPlay(c) { const u = c.target('ally creature'); durationBuff(c, u, 3); c.status(u, 'Nature blade', { end: c.g.turnNumber }); } },
  // ELECTRIC
  'Lightning Stone': { onDeath: c => { c.enemy.shards = Math.max(0, c.enemy.shards - 2); } },
  'Lightning Gauntlet': { equip: true, onAttack(c, u, attacker) { if (attacker.zone === 'controllers') paralyze(c, u); } },
  'Spark Knight Blade': { equip: true, aura: c => equipAura(c, 2, 0, { noRecoil: true }) },
  'The Luminary': { spellPlayed(c, card, side) { if (side === c.side && card.element === 'electric') spellArea(c, 1); }, active: [active('Thunder blessing', c => { const u = c.target('any creature'); durationBuff(c, u, 4); haste(c, u); }, 3)] },
  'Spark White Dragon': { onAttack(c, target) { if (c.attached().length) { const u = c.target('enemy unit', true, u => u.uid !== target.uid); if (u) c.damage(u, 2); } }, active: [active('Lightning burst', c => c.damage(c.target('enemy unit'), 5), 4)] },
  'Spark Knight': { active: [active('Disrupt passive', c => c.status(c.target('enemy unit'), 'Passive disabled', { remaining: 1 }), 2)] },
  'Volt-Howler': {},
  'Lightning Giant': { onAttack: (c, u) => paralyze(c, u) },
  'Lightning Samurai': { onKill: c => c.damage(c.controller(c.opponent), c.source.currentAP) },
  'Lightning Zephyr Knight': { onPlay(c) { const card = c.search(['Zephyr'], ['hand', 'deck']); if (card) { c.me.hand.splice(c.me.hand.indexOf(card), 1); c.source.flags.zephyr = true; c.buff(c.source, 2, 2); } } },
  'Viking of Light': { aura(c) { if (c.controller() && c.attached(c.controller()).length) c.source.traits.stealth = true; } },
  'Lightning Knight': { traits: { reduction: 1 } },
  'Lightning Mage': { onPlay(c) { for (const a of c.me.artifacts.filter(u => u?.target)) { const target = c.field().find(u => u.uid === a.target); if (target) durationBuff(c, target, 2); } } },
  'Lightning Wielder': { active: [active('Transfer artifact', c => { const a = c.target('ally artifact', false, u => !!u.target); const target = c.target('ally unit'); a.target = target.uid; })] },
  'Cosmic Witch': {},
  'Spirit of Lightning': { active: [active('Sacrifice for energy', c => { c.destroy(c.source, 'sacrifice'); c.gain(2, true); })] },
  'Zephyr': { active: [active('Equip to Lightning Zephyr Knight', c => { const target = c.target('ally creature', false, u => u.card.name === 'Lightning Zephyr Knight'); c.destroy(c.source, 'sacrifice'); target.flags.zephyr = true; c.buff(target, 2, 2); })] },
  'Binding Chains of Lightning': { persistent: true, priority: 10, onPlay(c) { const u = c.target('enemy creature'); c.source.target = u.uid; c.status(u, 'Lightning chains', { source: c.source.uid }); c.status(u, 'Paralyzed', { source: c.source.uid }); }, aura(c) { const u = c.targetUnit(); if (u) u.currentAP -= elemental(c, 'electric').length; } },
  'Surreal Light': { onPlay(c) { const u = c.target('ally creature', false, u => u.card.element === 'electric'); durationBuff(c, u, 4); haste(c, u); c.status(u, 'Surreal', { end: c.g.turnNumber }); } },
  'Wolf Lightning Strike': { onPlay(c) { const u = c.target('enemy unit'); c.damage(u, 4); if (!c.alive(u) && u.zone === 'creatures') c.damage(c.controller(c.opponent), 4); } },
  // FIRE
  'Cursed Flame Sword': { equip: 'ally creature', aura: c => equipAura(c, 3), onAttack(c, _, u) { if (u.card.name !== 'Draco' || c.g.turnNumber - c.source.summonedTurn >= 4) c.damage(c.controller(), 1); } },
  'Flame Orb': { equip: 'ally creature', onPlay(c) { const u = c.targetUnit(); need(u.card.element === 'fire', 'Flame Orb requires a Fire creature.'); durationBuff(c, u, u.currentAP); destroyEnd(c, u, { explode: 2 }); } },
  "Draco's Slayer": { equip: 'ally creature', onPlay(c) { const modes = []; if (c.has('Draco')) modes.push('Equip Draco'); if (enemies(c).some(u => u.currentAP >= 6)) modes.push('Destroy a 6+ AP enemy'); const mode = c.choose('Use Draco’s Slayer as equipment or removal?', modes, v => v); if (mode === 'Destroy a 6+ AP enemy') { c.destroy(c.target('enemy creature', false, u => u.currentAP >= 6), 'spell'); c.destroy(c.source, 'expiry'); } else { const u = c.target('ally creature', false, u => u.card.name === 'Draco'); c.source.target = u.uid; c.buff(u, 3, 0, 2, 'Draco’s Slayer'); } } },
  'Draco Alec': { aura: c => buffAura(c, 'fire', 1), active: [active('Fateful assault', c => { const u = c.target('ally creature', false, u => u.card.element === 'fire'); attackTwice(c, u); destroyEnd(c, u); })] },
  'Flame Emperor': { active: [active('Flame insight', c => c.draw(), 2), active('Imperial fire', c => c.damage(c.controller(c.opponent), 2), 2)] },
  'Supreme Fire Spirit': { aura: c => buffAura(c, 'fire', 1), active: [active('Incinerate', c => c.destroy(c.target('enemy creature', false, u => u.currentCH <= 4)), 3)] },
  'Draco': { aura(c) { if (c.has('Draco Alec')) c.source.currentAP += 2; } },
  "Emperor's Fire Dragon": { aura(c) { if (c.has('Flame Emperor')) c.source.traits.double = true; }, active: [active('Dragon flame', c => c.damage(c.target('enemy creature'), 3), 2)] },
  'Flame Dragon': { traits: { bypassSwarm: true } },
  'Fire Paladin': { onKill: c => healController(c, 2) },
  'Flame Samurai': { traits: { firstStrike: true } },
  'Fire Knight': { traits: { haste: true } },
  'Flaming Sword Bearer': { onDeath: c => c.search(['Cursed Flame Sword', 'Katana of Fate']) },
  'Flame Guardian': { traits: { cannotAttack: true, guardian: true } },
  'Flame Wolf': { onPlay: c => c.flag('wolfTurn', c.g.turnNumber) },
  'Fire Witch': { onPlay: c => c.damage(c.controller(c.opponent), 1) },
  'Flame Warlock': { active: [active('Sacrificial fire', c => { const target = c.target('enemy creature'); sacrifice(c); c.damage(target, 3); })] },
  "Draco's Inferno": { require: c => need(c.has('Draco') || c.has('Draco Alec'), 'Requires Draco or Draco Alec.'), onPlay(c) { const both = c.has('Draco') && c.has('Draco Alec'); c.aoe(both ? 5 : 3, [...allies(c), ...enemies(c)]); if (both) c.damage(c.controller(c.opponent), 2); } },
  "Draco's Curse": { require: c => need(c.has('Draco Alec'), 'Requires Draco Alec.'), onPlay(c) { const u = c.target('enemy creature'); c.steal(u); u.flags.dracoCurse = c.side; } },
  'Enflamed': { onPlay(c) { const u = c.target('enemy creature'); if (c.has('Supreme Fire Spirit')) { u.flags.enflamed = { side: c.side, amount: Math.min(6, u.currentCH) }; c.status(u, 'Doomed', { remaining: 1, destroy: true }); } else c.destroy(u); } },
  // LIGHT
  'Dagger of Fate': { equip: 'ally creature', aura: c => equipAura(c, 2), onAttack(c, u) { if (u.zone === 'controllers') c.discard(); } },
  'Sword of the Sun Guardian': { equip: 'ally creature', aura(c) { equipAura(c, 4); const u = c.targetUnit(); if (u?.card.name === 'Sun Knight') { u.traits.stealth = true; u.traits.halfControllerDamage = true; } } },
  'Cosmic Sunlight Goddess': { aura: c => buffAura(c, 'light', 1), active: [active('Seal artifacts', c => { c.enemy.locks.artifacts = 2; }, 4)] },
  'Perfect Light Being': { active: [active('Light restraint', c => bind(c, c.target('enemy unit'), 2), 3)] },
  'Light Priest': { turnStart(c, side) { if (onOwnTurn(c, side)) elemental(c, 'light').forEach(u => c.heal(u, 1)); }, active: [active('Healing light', c => c.heal(c.target('any unit'), 3), 2)] },
  'Michael': { require: c => need(c.me.flags.divineTurn === c.g.turnNumber, 'Play Divine Light this turn first.'), onAttack(c, u) { c.status(u, 'Silenced'); c.status(u, 'No healing'); } },
  'Light Dragon': { onAttack(c, target) { c.aoe(2, enemies(c).filter(u => u.uid !== target.uid)); } },
  'Sun Golem': { traits: { cannotAttack: true, reflect: true } },
  'Sun Guardian': { aura(c) { for (const u of [...c.me.controllers, ...c.me.spells].filter(Boolean)) u.traits.spellUntargetable = true; } },
  'Sun Commander': { onPlay: c => elemental(c, 'light').forEach(u => durationBuff(c, u, 2)) },
  'Sun Knight': { traits: { guardianController: true } },
  'Radiant Witch': { onPlay(c) { const u = c.target('any creature'); c.status(u, 'Spell immunity', { trait: 'spellImmune' }); } },
  'Sun Mage': { active: [active('Solar bolt', c => c.damage(c.target('any unit'), 2), 1)] },
  'Sun Wolf': { traits: { haste: true }, onPlay(c) { if (c.g.turnNumber >= 3) { const target = c.target('enemy unit', true); if (target) c.attackNow(target); } } },
  'Sun Fairy': { active: [active('Sacrifice for shards', c => { c.destroy(c.source, 'sacrifice'); c.gain(2); })] },
  'Light Spirit': { priority: 20, aura(c) { const bound = enemies(c).find(u => u.statuses['Light Bind']); if (bound) { c.source.currentAP += Math.max(0, bound.currentAP); c.source.maxCH += bound.maxCH; } } },
  'Divine Light': { require: c => need(c.has('Light Enchantment'), 'Light Enchantment is required.'), onPlay(c) { const u = c.controller(); u.damage = Math.max(0, u.maxCH - 12); c.flag('divineTurn', c.g.turnNumber); } },
  'Light Bind': { onPlay(c) { const u = c.target('enemy creature'); bind(c, u, 2, true); c.status(u, 'Light Bind', { remaining: 2 }); } },
  'Burning Blast': { onPlay(c) { const u = c.target('enemy unit'); c.damage(u, 3); if (!c.alive(u)) c.gain(1); } },
  'Light Enchantment': { persistent: true, equip: 'ally controller', onPlay(c) { const u = c.targetUnit(); const half = Math.ceil(u.currentCH / 2); u.damage += half; c.buff(u, half); }, onDeath(c) { const u = c.targetUnit(); if (u) c.destroy(u, 'ability'); } },
  'Divine Elemental Convergence': { persistent: true, aura: c => c.field().filter(u => u.card.element === 'light').forEach(u => { u.currentAP++; }), turnEnd(c) { if (!elemental(c, 'light').length) c.destroy(c.source, 'expiry'); } },
  // SHADOW
  "Thor's Hammer": { equip: 'ally creature', aura: c => equipAura(c, 5), onAttack(c, target) { c.aoe(1, enemies(c).filter(u => u.uid !== target.uid)); } },
  'Cursed Sword': { equip: 'ally creature', aura: c => equipAura(c, 4, 0, { bypassSwarm: true }), turnEnd(c) { c.damage(c.targetUnit(), 2, 'healthLoss'); } },
  'Dark Orb': { equip: true, onDamage(c) { const options = c.me.deck.slice(0, 3).filter(card => card.element === 'shadow' && card.card_type === 'spell'); const card = c.choose('Take a Shadow spell from the top three', options, v => v.name, true); if (card) { c.me.deck.splice(c.me.deck.indexOf(card), 1); c.me.hand.push(card); } }, onDeath(c, { cause }) { if (cause === 'sacrifice') c.draw(2); } },
  'Darth Ayres': { aura: c => enemies(c).forEach(u => { u.currentAP--; }), active: [active('Dark nova', c => spellArea(c, 2), 4)] },
  'Umbra Reaver': { active: [active('Soul drain', c => { c.damage(c.target('enemy unit'), 2); healController(c, 2); }, 2)] },
  'Shadow Master': { active: [active('Dark dimension', c => c.banish(c.target('any creature'), 2), 3)] },
  'Dark Samurai': { aura(c) { c.source.currentAP += c.me.graveyard.filter(card => card.element === 'shadow').length; } },
  'Dark Phantom': { traits: { stealth: true } },
  'Dark Knight': {},
  'Shadow Knight': {},
  'Dark Warlock': { onPlay: c => c.discard() },
  'Sigurd Shadowhand': { onAttack: c => c.discard() },
  'Shadow Wraith': { onKill: c => c.buff(c.source, 1) },
  'Night Terror': { onDamage: (c, u) => bind(c, u, 1) },
  'Dark Dimension': { onPlay: c => c.banish(c.target('any creature'), 2) },
  'Black Spell': { onPlay(c) { const before = new Set(allies(c).map(u => u.uid)); c.token('Shadow Token', 2, 2, 2); if (c.has('Dark Warlock') && c.me.creatures.some(u => !u)) { const card = c.search(card => card.element === 'shadow' && card.card_type === 'creature', ['hand']); if (card) { c.me.hand.splice(c.me.hand.indexOf(card), 1); c.summon(card); } } for (const u of allies(c).filter(u => !before.has(u.uid))) c.status(u, 'Summoning lock', { trait: 'cannotAttack', end: c.g.turnNumber }); } },
  'Dark Ritual': { onPlay(c) { const u = c.choose('Choose a creature or Dark Orb to sacrifice', [...allies(c).filter(u => !u.traits.cannotSacrifice), ...c.me.artifacts.filter(u => u?.card.name === 'Dark Orb')]); for (const a of c.attached(u)) if (a.card.name === 'Dark Orb') c.destroy(a, 'sacrifice'); c.destroy(u, 'sacrifice'); c.gain(5); if (c.has('Shadow Master')) { c.search(["Shadow's Embrace"], ['deck']); const card = c.search(v => v.card_type === 'creature', ['hand']); if (card) { c.me.hand.splice(c.me.hand.indexOf(card), 1); c.summon(card); } } } },
  "Shadow's Embrace": { onPlay(c) { c.steal(c.target('enemy creature')); if (c.has('Darth Ayres') && c.enemy.hand.length && c.me.creatures.some(u => !u)) { const card = c.choose('Take a hand card as a shield', c.enemy.hand); c.enemy.hand.splice(c.enemy.hand.indexOf(card), 1); c.token(`Shield of ${card.name}`, 0, card.ch || 1, 1, { guardian: true }); const shield = allies(c).findLast(u => u.card.token); shield.flags.stolenCard = card; shield.flags.shield = true; } } },
  'Dark Chains': { persistent: true, priority: 10, onPlay(c) { const u = c.target('any creature'); c.source.target = u.uid; if (u.side === c.side) { c.status(u, 'Dark shield', { source: c.source.uid, trait: 'guardian' }); } else c.status(u, 'Paralyzed', { source: c.source.uid }); }, aura(c) { const u = c.targetUnit(); if (u && u.side !== c.side) { const amount = Math.max(0, u.currentAP); for (const knight of allies(c).filter(v => ['Dark Knight', 'Shadow Knight'].includes(v.card.name))) knight.currentAP += amount; u.currentAP = 0; } } },
  'Shadow Spell': { onPlay(c) { const u = c.target('ally creature', false, u => u.card.element === 'shadow'); c.buff(u, 2); c.status(u, 'Stealth', { trait: 'stealth' }); if (u.card.name === 'Dark Phantom') shield(c, u, 'spellUntargetable', 1); if (u.card.name === 'Dark Samurai') { const target = c.choose('Destroy enemy artifact or spell', [...c.enemy.artifacts, ...c.enemy.spells].filter(Boolean), v => v.card.name, true); if (target) c.destroy(target); } } },
  'Dark Nova': { onPlay(c) { const targets = c.has('Darth Ayres') ? enemies(c) : [...allies(c), ...enemies(c)]; c.me.nextShards += c.aoe(3, targets); } },
  'Elemental Convergence': { persistent: true, onPlay(c) { c.source.flags.element = c.choose('Choose the enemy element', ['blood', 'cryo', 'earth', 'electric', 'fire', 'light', 'shadow', 'water', 'wind'], v => v); } },
  'Creature Recall': { onPlay(c) { const card = c.search(v => ['creature', 'controller'].includes(v.card_type), ['graveyard'], false); if (card.card_type === 'controller') card.card_type = 'creature'; } },
  // WATER
  'Spear of Neptune': { equip: true, aura: c => equipAura(c, 4), onDamage(c, u) { if (c.alive(u) && u.zone === 'creatures') c.bounce(u); } },
  'Crown of Neptune': { spellPlayed(c, card, side) { if (side === c.side && card.element === 'water') c.gain(1); } },
  'Neptune': { onPlay(c) { c.search(['Water Safe']); if (c.has('The Kraken')) copyFrom(c, 'Kraken Slash'); } },
  'The Kraken': { spellPlayed(c, card, side) { if (side === c.side && card.element === 'water') c.enemy.shards = Math.max(0, c.enemy.shards - 1); }, active: [active('Prepare Ink Cloud', c => { c.me.reaction = { name: 'Ink Cloud' }; }, 3)] },
  'Mermaid Empress': { aura(c) { allies(c).filter(u => ['Water Guardian', 'Royal Guard', 'Guardians of Atlantis'].includes(u.card.name)).forEach(u => { u.currentAP += 2; }); }, active: [active('Deep recovery', c => c.heal(c.target('ally creature', false, u => u.card.element === 'water'), 4), 2)] },
  'Supreme Water Dragon': { onPlay: c => [...enemies(c)].filter(u => u.currentAP <= 4).forEach(u => c.bounce(u)) },
  'Water Golem': { traits: { guardian: true, waterGolem: true } },
  'Guardians of Atlantis': {},
  'Shark': {},
  'Royal Guard': {},
  'Lizard Warrior': { aura(c) { if (c.me.flags.waterSpellTurn === c.g.turnNumber) { c.source.currentAP += 2; c.source.traits.double = true; } } },
  'Water Warlock': { onDamage(c, u) { if (u.zone === 'creatures' && c.enemy.shards > 0) { c.enemy.shards--; c.gain(1); } } },
  'Water Guardian': {},
  'Water Familiar': { active: [active('Seal an enemy spell', c => { const card = c.choose('Choose a spell to seal for two turns', c.enemy.hand.filter(v => v.card_type === 'spell')); c.enemy.banned[card.id] = 2; c.destroy(c.source, 'sacrifice'); })] },
  'Whirlpool': { onPlay(c) { c.enemy.locks.spells = 1; if (c.enemy.spells.some(Boolean)) { c.destroy(c.target('enemy spell')); copyFrom(c, 'Tidal Wave'); } } },
  'Water Entrapment': { onPlay(c) { const u = c.target('enemy creature'); if (u.card.element === 'fire') c.destroy(u); else paralyze(c, u, 3); } },
  'Kraken Slash': { onPlay(c) { const u = c.target('enemy unit'); c.damage(u, 5); if (c.alive(u) && u.zone === 'creatures') c.bounce(u); } },
  'Tidal Wave': { onPlay: c => [...allies(c), ...enemies(c)].filter(u => u.card.element !== 'water').forEach(u => c.bounce(u)) },
  "Dragon's Tsunami": { require: c => need(c.has('Supreme Water Dragon'), 'Requires Supreme Water Dragon.'), onPlay(c) { for (const u of [...enemies(c)]) if (u.currentCH <= 3) c.destroy(u); else c.bounce(u); } },
  'Water Safe': { persistent: true, aura: c => c.units().filter(u => u.card.element === 'water').forEach(u => { u.traits.waterSafe = true; }), turnStart(c, side) { if (!onOwnTurn(c, side)) return; const empress = c.named('Mermaid Empress'); if (!empress || empress.currentCH <= 1) c.destroy(c.source, 'expiry'); else empress.damage++; } },
  // WIND
  'Wind Orb': { aura: c => buffAura(c, 'wind', 1, 1) },
  'Wind Staff': { equip: true, onAttack: c => c.discard() },
  'Wind Sword': { equip: true, aura: c => equipAura(c, 2, 2), onDamage(c, target, source) { if (source.card.name === 'Wind Keeper' && source.flags.recallTurn !== c.g.turnNumber && c.alive(target) && target.zone === 'creatures') { source.flags.recallTurn = c.g.turnNumber; c.bounce(target); } } },
  'Wind Knight': { aura: c => elemental(c, 'wind').forEach(u => { u.traits.haste = true; }), active: [active('Ronin strike', c => attackTwice(c, c.target('ally unit')), 3)] },
  'Wind Witch': { active: [active('Mirage veil', c => shield(c, c.target('ally unit'), 'spellUntargetable', 1), 2)] },
  'Spirit of the Wind': { aura(c) { if (c.has('Smoke Body')) c.source.traits.stealth = true; } },
  'Wind Dragon': { onAttack(c, target) { c.aoe(2, enemies(c).filter(u => u.uid !== target.uid)); } },
  'Wind Golem': { traits: { guardian: true, combatReduction: 3 } },
  'Wind Ronin': { traits: { double: true } },
  'Wind Warrior': { onPlay: c => c.buff(c.target('ally unit'), 2), aura(c) { if (allies(c).some(u => u.owner !== c.side)) c.source.currentAP += 2 * elemental(c, 'wind').length; } },
  'Wind Warlock': {},
  'Wind Keeper': {},
  'Wind Pack': { onPlay(c) { if (!c.source.flags.suppressRecruit && c.me.creatures.some(u => !u)) c.fromZone(['Wind Pack'], ['deck'], { suppressRecruit: true }); } },
  'Tempest': { onPlay(c) { const n = c.me.flags.recalled || 0; c.damage(c.controller(c.opponent), n); if (n >= 3) c.draw(); } },
  'Wind Control': { onPlay: c => c.steal(c.target('enemy creature'), 2) },
  'Sweeping Wind': { onPlay(c) { const targets = c.has('Wind Dragon') ? enemies(c) : [...allies(c), ...enemies(c)]; targets.forEach(u => c.bounce(u)); const card = c.me.deck.shift(); if (!card) return; if (card.card_type === 'spell') { c.me.hand.push(card); c.playFree(card); } else if (card.card_type === 'creature') { c.me.deck.splice(Math.floor(c.random() * (c.me.deck.length + 1)), 0, card); } else c.me.hand.push(card); } },
  'Spell Release': { onPlay(c) { if (c.controller()?.card.name === 'Wind Warlock') c.enemy.spells.filter(Boolean).forEach(u => c.destroy(u)); else c.destroy(c.target('any spell')); } },
  'Dark Infusion': { onPlay(c) { if (c.has('Wind Warlock')) c.search(['Wind Control']); else c.damage(c.controller(c.opponent), 3); } },
  'Wind Protection': { require: c => need(elemental(c, 'wind').length >= 2, 'Requires at least two Wind allies.'), onPlay(c) { elemental(c, 'wind').forEach(u => shield(c, u, 'cannotBeAttacked', 3)); } },
  'Smoke Body': { persistent: true, equip: 'ally unit', turnStart(c, side) { if (onOwnTurn(c, side)) c.destroy(c.source, 'expiry'); }, aura: c => equipAura(c, 0, 0, { invulnerable: true, untargetable: true }) },
  'Wind Mirage': { onPlay(c) { c.me.reaction = { name: 'Wind Mirage' }; c.note('Wind Mirage is prepared for the next attack on your controller.'); } },
};

// Explicit prototype interpretations for text that does not fully specify timing or values.
export const interpretations = {
  'Reaper': 'Kills do not refund attacks. The current game has no separate block/exhaust phase.',
  'Frozen Spirit': 'Returns after dealing attack damage. A Frozen enemy creature still protects its Controller; bypass requires Stealth.',
  "Draco's Slayer": 'Choose equipment or removal when played. Equipment requires Draco; removal requires a 6+ AP creature.',
  'Sun Wolf': 'On summon, choose an immediate attack when the first-two-turn attack lock permits it.',
  "Shadow's Embrace": 'The stolen hand card becomes a 0/base-CH Guardian token (minimum 1 CH); sacrifice it to heal that CH.',
  'The Kraken': 'Ink Cloud is prepared in main phase and intercepts the next attack; target selection belongs to the defender.',
  'Wind Mirage': 'Prepared in main phase; cancels the next controller attack and summons a defensive Wind Golem if a slot is available.',
  'Binding Chains of Lightning': 'While AP is zero, damage is redirected to the lowest-CH enemy controller.',
  'Sphere of Ice': 'Protector/Knight means Ice Protector or Frozen Knight from hand/deck.',
  'Defrost': 'Cleanses Freeze, Paralyze and Bind; +3 AP lasts through the current End Phase.',
  'Enflamed': 'With Supreme Fire Spirit, the target survives until the end of its next turn, then explodes for its marked CH, capped at 6 damage.',
  'Dark Ritual': 'The Shadow Master bonus resolves its free summon immediately. Out-of-turn instant-speed casting requires the future response-stack implementation.',
  'Vampiric Destiny': 'Search, health grant, and marked-creature return are implemented. There is no interruption window in this solo preview.',
  'Spell Release': 'The Wind Warlock controller condition is recognized, but this preview has no creature-to-controller promotion action.',
  'Light Spirit': 'The Light Bind stat-copy synergy is implemented. The supplied list does not define any separate rule for the Vessel keyword.',
  "Nature's Blade": 'The +3 AP and draw-on-kill effect last until the current End Phase in this preview.',
};
