import { useEffect, useRef, useState } from 'react';
import { Diamond, Plus, ArrowLeft } from 'lucide-react';
import { AuthProvider, useAuth } from '../lib/AuthContext';
import { supabase } from '../lib/supabaseClient';
import { cards, elements } from '../practice/catalog';
import StrictAbilityBuilder from '../components/admin/StrictAbilityBuilder';
import '../practice/practice.css';
import '../store/store.css';
import './admin.css';
const freshCard=()=>({code:`DRAFT_${crypto.randomUUID().slice(0,8).toUpperCase()}`,name:'',card_type:'creature',element:'fire',rarity:'common',cost:1,ap:1,ch:1,description:'',art_url:'',keywords:[],abilities:[]});
const freshPromo=()=>({code:'',tokens:0,max_uses:1,is_active:true,expires_at:'',description:'',rewards:[]});
async function request(body){const {data,error}=await supabase.functions.invoke('admin',{body});if(error){let message;try{message=(await error.context.json()).error;}catch{/* lost response */}const failure=new Error(message||'Connection interrupted. Retry your last save.');failure.definitive=error.context?.status>=400&&error.context?.status<500;throw failure;}return data;}
function Admin(){
 const {user,loading}=useAuth();const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('cards'),[query,setQuery]=useState('');
 const [card,setCard]=useState(freshCard),[cardVersion,setCardVersion]=useState(0),[promo,setPromo]=useState(freshPromo),[promoVersion,setPromoVersion]=useState(-1),[pending,setPending]=useState(null);
 const lock=useRef(false);const generation=useRef(0);
 async function load(){const next=await request({op:'list'});setData(next);return next;}
 useEffect(()=>{const current=++generation.current;setData(null);setError('');setPending(null);if(user){request({op:'list'}).then(next=>{if(current===generation.current)setData(next);}).catch(e=>{if(current===generation.current)setError(e.message);});try{setPending(JSON.parse(sessionStorage.getItem(`fatebound.admin.pending.${user.id}`)||'null'));}catch{/* ignore damaged cache */}}return()=>{generation.current++;};},[user?.id]);
 async function save(op,payload,version,retry){
  if(lock.current)return;lock.current=true;setBusy(true);setNotice('');const body=retry||{op,data:payload,version,requestId:crypto.randomUUID()};
  setPending(body);sessionStorage.setItem(`fatebound.admin.pending.${user.id}`,JSON.stringify(body));
  try{await request(body);setPending(null);sessionStorage.removeItem(`fatebound.admin.pending.${user.id}`);const next=await load();
   if(body.op==='save_card'){const saved=next.drafts.find(d=>d.code===body.data.code.toUpperCase());setCard(saved.data);setCardVersion(saved.version);setNotice('Card draft saved. It is ready for rules review.');}
   else if(body.op==='save_promo'){const saved=next.promos.find(p=>p.code===body.data.code.toUpperCase());setPromo(saved);setPromoVersion(saved.admin_version);setNotice(saved.is_active?'Promo saved and available in the store.':'Promo saved and disabled.');}
   else {setCard(freshCard());setCardVersion(0);setNotice('Draft archived. You can reopen it below.');}
  }catch(e){if(e.definitive){setPending(null);sessionStorage.removeItem(`fatebound.admin.pending.${user.id}`);}setNotice(e.message);}finally{lock.current=false;setBusy(false);}
 }
 const editCard=(key,value)=>setCard(c=>({...c,[key]:value}));const editPromo=(key,value)=>setPromo(p=>({...p,[key]:value}));
 const blocked=busy||!!pending;const filtered=cards.filter(c=>`${c.name} ${c.id}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="fate-app admin-app"><header className="fate-header"><a className="brand" href="/"><Diamond/><span>FATEBOUND<small>SHARDS OF DOMINION</small></span></a><nav className="header-tools"><a href="/">Arena</a><a href="/store">Card store</a></nav></header><main className="store-main"><a href="/store" className="store-back"><ArrowLeft size={15}/> Back to store</a><p className="eyebrow">OWNER TOOLS</p><h1>The creator’s desk.</h1>
  {loading?<p>Checking your account…</p>:!user?<p><a href="/store">Sign in at the store</a> and redeem your owner code to unlock admin tools.</p>:!data?<section><p role="alert">{error||'Checking admin access…'}</p>{error&&<><p>Redeem your owner code in the store’s promo field. Access stays with the account that redeems it first.</p><a href="/store">Open the store</a><button onClick={()=>load().then(()=>setError('')).catch(e=>setError(e.message))}>Check access again</button></>}</section>:<>
   <nav className="store-tabs"><button aria-current={tab==='cards'?'page':undefined} onClick={()=>setTab('cards')}>Card creator</button><button aria-current={tab==='promos'?'page':undefined} onClick={()=>setTab('promos')}>Promo codes</button></nav>
   <p role="status" className="store-notice">{notice}</p>{pending&&<section className="store-retry"><p>A save needs confirmation. Retrying uses the same request.</p><button disabled={busy} onClick={()=>save(null,null,null,pending)}>Retry last save</button></section>}
   {tab==='cards'?<><p>Create cards, edit their stats and artwork, and describe abilities. Drafts are saved separately from the tested live cards. They enter battles and store packs after their rules are implemented and published.</p>
    <div className="admin-workbench"><form onSubmit={e=>{e.preventDefault();void save('save_card',card,cardVersion);}}><div className="store-section-heading"><h2>{cardVersion?'Edit draft':'New card'}</h2><button type="button" disabled={blocked} onClick={()=>{setCard(freshCard());setCardVersion(0);}}>New draft</button></div>
     <div className="admin-grid"><label>Card code<input required pattern="[A-Za-z0-9_-]{2,64}" maxLength={64} disabled={cardVersion>0} value={card.code} onChange={e=>editCard('code',e.target.value.toUpperCase())}/></label><label>Name<input required maxLength={100} value={card.name} onChange={e=>editCard('name',e.target.value)}/></label>
      {[['card_type','Type',['creature','controller','spell','artifact','token']],['element','Element',[...elements,'neutral','universal','hybrid']],['rarity','Rarity',['common','uncommon','rare','epic','legendary']]].map(([key,label,options])=><label key={key}>{label}<select value={card[key]} onChange={e=>editCard(key,e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>)}
      {[['cost','Shard cost',100],['ap','Attack',999],['ch','Health',999]].map(([key,label,max])=><label key={key}>{label}<input type="number" min={0} max={max} required value={card[key]} onChange={e=>editCard(key,Number(e.target.value))}/></label>)}</div>
     <label>Rules text<textarea maxLength={4000} value={card.description} onChange={e=>editCard('description',e.target.value)}/></label><label>Artwork URL<input type="url" placeholder="https://…" maxLength={2000} value={card.art_url} onChange={e=>editCard('art_url',e.target.value)}/></label><label>Keywords (comma separated)<input key={`${card.code}:${cardVersion}`} defaultValue={card.keywords.join(', ')} onChange={e=>editCard('keywords',e.target.value.split(',').map(s=>s.trim()).filter(Boolean))}/></label>
     <h3>Ability design</h3><p>These are design specifications; saving them does not add untested effects to live matches.</p><StrictAbilityBuilder abilities={card.abilities} onChange={value=>editCard('abilities',value)} tokenCards={data.drafts.filter(d=>d.data.card_type==='token').map(d=>d.data)}/>
     <button className="primary" disabled={blocked}>Save card draft</button>{cardVersion>0&&<button type="button" disabled={blocked} onClick={()=>save('archive_card',{code:card.code},cardVersion)}>Archive draft</button>}
    </form><aside><div className="admin-card-preview">{card.art_url.startsWith('https://')&&<img src={card.art_url} alt="Card artwork preview" onError={e=>{e.currentTarget.style.visibility='hidden';}} onLoad={e=>{e.currentTarget.style.visibility='visible';}}/>}<p className="eyebrow">DRAFT · {card.element} · {card.rarity}</p><h2>{card.name||'Your new card'}</h2><p>{card.cost} shards · {card.card_type}</p><strong>{card.ap} attack / {card.ch} health</strong><p>{card.description||'Your card’s rules text appears here.'}</p></div>
     <h3>Saved drafts</h3>{data.drafts.map(d=><button disabled={blocked} className="admin-list-item" key={d.code} onClick={()=>{setCard(d.data);setCardVersion(d.version);}}>{d.data.name}<small>{d.code} · v{d.version}{d.archived?' · archived':''}</small></button>)}
    </aside></div><h2>Start from a current card</h2><input aria-label="Search current cards" placeholder="Search cards…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="admin-card-list">{filtered.map(c=><button disabled={blocked} key={c.id} onClick={()=>{setCard({...freshCard(),name:c.name,card_type:c.card_type,element:c.element,cost:c.cost,ap:c.ap||0,ch:c.ch||0,description:c.description,art_url:c.image_url||'',rarity:data.catalog.find(x=>x.id===c.id)?.rarity||'common'});setCardVersion(0);window.scrollTo({top:0,behavior:'smooth'});}}>{c.name}<small>{c.element} · {c.card_type}</small></button>)}</div></>:
    <div className="admin-workbench"><form onSubmit={e=>{e.preventDefault();void save('save_promo',promo,promoVersion);}}><div className="store-section-heading"><h2>{promoVersion<0?'Create promo':'Edit promo'}</h2><button type="button" disabled={blocked} onClick={()=>{setPromo(freshPromo());setPromoVersion(-1);}}>New promo</button></div><div className="admin-grid"><label>Promo code<input required pattern="[A-Za-z0-9_-]{2,64}" maxLength={64} disabled={promoVersion>=0} value={promo.code} onChange={e=>editPromo('code',e.target.value.toUpperCase())}/></label><label>Tokens<input type="number" min={0} max={1000000} required value={promo.tokens||0} onChange={e=>editPromo('tokens',Number(e.target.value))}/></label><label>Total redemption limit<input type="number" min={Math.max(1,promo.current_uses||0)} max={1000000} required value={promo.max_uses??1} onChange={e=>editPromo('max_uses',Number(e.target.value))}/></label><label>Expires at (optional, UTC)<input type="datetime-local" value={promo.expires_at?new Date(promo.expires_at).toISOString().slice(0,16):''} onChange={e=>editPromo('expires_at',e.target.value?`${e.target.value}:00Z`:'')}/></label></div><label>Description<textarea maxLength={1000} value={promo.description||''} onChange={e=>editPromo('description',e.target.value)}/></label><label className="admin-check"><input type="checkbox" checked={promo.is_active} onChange={e=>editPromo('is_active',e.target.checked)}/> Active in the store</label>
     <h3>Card rewards</h3><p>Choose cards from the current live catalog. Each player can redeem a code once.</p>{promo.rewards.map((r,i)=><div className="admin-reward-row" key={i}><select aria-label={`Reward card ${i+1}`} required value={r.card_id||''} onChange={e=>editPromo('rewards',promo.rewards.map((x,j)=>i===j?{...x,card_id:e.target.value}:x))}><option value="">Choose a card</option>{data.catalog.map(c=><option value={c.id} key={c.id}>{c.name} ({c.element})</option>)}</select><input aria-label={`Quantity ${i+1}`} type="number" min={1} max={100} required value={r.quantity} onChange={e=>editPromo('rewards',promo.rewards.map((x,j)=>i===j?{...x,quantity:Number(e.target.value)}:x))}/><button type="button" onClick={()=>editPromo('rewards',promo.rewards.filter((_,j)=>i!==j))}>Remove</button></div>)}<button type="button" disabled={promo.rewards.length>=50} onClick={()=>editPromo('rewards',[...promo.rewards,{card_id:'',quantity:1}])}><Plus size={14}/> Add card reward</button><p>{promo.current_uses||0} redemptions used. Editing keeps all redemption history.</p><button disabled={blocked} className="primary">Save promo code</button>
    </form><aside><h2>Your promo codes</h2>{data.promos.map(p=><button disabled={blocked} className="admin-list-item" key={p.code} onClick={()=>{setPromo({...p,rewards:p.rewards||[]});setPromoVersion(p.admin_version);}}>{p.code}<small>{p.is_active?'Active':'Disabled'} · {p.current_uses||0}/{p.max_uses??'∞'} used · {p.tokens||0} tokens</small></button>)}</aside></div>}
  </>}
 </main></div>;
}
export default function AdminApp(){return <AuthProvider><Admin/></AuthProvider>;}
